const {
    outputDirectory,
    rootDirectory,
    publicDirectory,
    environmentsDirectory,
    jestDirectory,
  } = require('./constants'),
  { resolveApp } = require('./helpers');

module.exports = {
  srcPath: resolveApp(rootDirectory),
  appIndexPath: resolveApp(`${rootDirectory}/index`),
  assetsDirPath: resolveApp(`${rootDirectory}/assets`),
  constantsDirPath: resolveApp(`${rootDirectory}/constants`),
  managersDirPath: resolveApp(`${rootDirectory}/managers`),
  routingDirPath: resolveApp(`${rootDirectory}/routing`),
  storeDirPath: resolveApp(`${rootDirectory}/store`),
  servicesDirPath: resolveApp(`${rootDirectory}/services`),
  hooksDirPath: resolveApp(`${rootDirectory}/hooks`),
  pagesDirPath: resolveApp(`${rootDirectory}/pages`),
  componentsDirPath: resolveApp(`${rootDirectory}/components`),
  modelsDirPath: resolveApp(`${rootDirectory}/models`),
  dataDirPath: resolveApp(`${rootDirectory}/data`),
  utilsDirPath: resolveApp(`${rootDirectory}/utils`),
  stylesDirPath: resolveApp(`${rootDirectory}/scss`),
  contextsDirPath: resolveApp(`${rootDirectory}/contexts`),
  swSourcePath: resolveApp(`${rootDirectory}/serviceWorker/swSource`),
  swIconPath: (imageSrc) => resolveApp(`${publicDirectory}/${imageSrc}`),
  publicDirPath: resolveApp(publicDirectory),
  indexHtmlPath: resolveApp(`${publicDirectory}/index.html`),
  jestPath: resolveApp(jestDirectory),
  outputSrcPath: resolveApp(outputDirectory),
  envDevelopmentPath: resolveApp(`${environmentsDirectory}/.env.development`),
  envProductionPath: resolveApp(`${environmentsDirectory}/.env`),
};
